### ISSUE TITLE
Default to stdin when -f is not passed

### ISSUE THREAD

**Issue by oatberry** [HalosGhost/pbpst#10]
It'd be pretty nice if pbpst made stdin the default source of the paste when `-f` is not given on the command line for sync and update operations.

Progress to completion:
- [x] If `-f` (nor `-s` for paste-creation) is not specified, default to `stdin`
- [x] Document the change

**Comment by HalosGhost** [comment]
I don't have a problem with this. If `-f` and `-s` are not passed when `-S` or `-U` are, defaulting to `stdin` is pretty simple.

However, what do you mean for the delete option? Do you mean reading the UUID from `stdin`? If so, that's not going to happen. `-u`, like `-f` requires an argument (and since fixing this will fix the silly special-case we have given `-f`, it would seem really odd to me to add that silly special case to another option).

**Comment by oatberry** [comment]
Ok, that's fine. Thanks!

**Comment by HalosGhost** [comment]
Fixed via 9d23d28
