### ISSUE TITLE
Stopping reading from stdin with -S requires a double Ctrl+D

### ISSUE THREAD

**Issue by AladW** [HalosGhost/pbpst#32]
Tools like gist interrupt the paste with ^C, and stop reading from stdin with ^D. With pbpst, it goes like this:

```
pbpst -S
new foo bar
^D
^D
https://ptpb.pw/S5rr
```

Additionally, if Enter is not pressed after "new foo bar", ^D is required three times to get the link.

**Comment by HalosGhost** [comment]
For documentation, see [this SO post](https://stackoverflow.com/questions/1516122/how-to-capture-controld-signal/1516177#1516177).

Interestingly enough, `pbpst` does not directly read `stdin`. We just offload that responsibility to `libcurl`. I will research this a little more and see if `libcurl` has a simple way to deal with this case; and if not, I will close this as `INVALID` and report it upstream.

**Comment by HalosGhost** [comment]
As a brief update: it turns out that I could write a read function specifically to handle this case, ~~but I am not terribly motivated to do that; especially since `curl` has this same behavior. I am going to lower the severity of this, relabel from `Bug` to `Enhancement` and remove its slate from `1.0.0`. I may still choose to do the read function since it would be another improvement over using `curl`, but it is not as dire as I had originally thought.~~

A read function for this should not be terribly difficult and would make it far more intuitive for users.

**Comment by HalosGhost** [comment]
I cannot figure out how to get around using curl's callback function and I have no idea why curl itself is having this issue.

If someone else wants to step up and fix it; patches will be welcomed.
